### ISSUE TITLE
Geocode is triggered when trying update table that has address and coordinates

### ISSUE THREAD

**Issue by bogdandovgopol** [geocoder-php/BazingaGeocoderBundle#283] opened 2020-08-08 10:05 UTC
Hi,
I use annotations in my Entity to get coordinates and store them in a db table.
But when I try to update that entity without touching the address, it still triggers geocoding.
```
    /**
     * @ORM\Column(type="string", length=255)
     * @Geocoder\Address
     */
    private $location;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=8)
     * @Geocoder\Latitude()
     */
    private $latitude;

    /**
     * @ORM\Column(type="decimal", precision=11, scale=8)
     * @Geocoder\Longitude()
     */
    private $longitude;
```

Any ideas how to avoid that?

**Comment by norkunas** [comment] 2020-08-09 07:26
Duplicate of #280 ? Also I made a PR #281 but I can't merge it because of build status

**Closed** 2020-08-26 04:18 UTC
